name: Build and Push `netutil` Image to GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set Environment
        run: |
          echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and Push Docker Image [on pull_request]
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v2
        with:
          push: true
          labels: |
            org.opencontainers.image.description="Created from commit ${{ github.sha }}"
            org.opencontainers.image.revision=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.sha }}

      - name: Build and Push Docker Image [on push to master]
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          push: true
          labels: |
            org.opencontainers.image.description=A collection of network utilities\nSee: https://github.com/${{ github.repository }}\nCreated from commit: ${{ github.sha }}
            org.opencontainers.image.revision=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.sha }}
